"""initial data models

Revision ID: 3f8f86f0df5e
Revises:
Create Date: 2026-03-13 15:01:52.958272

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8f86f0df5e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("asset_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("price_change_24h", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("volume_24h", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("national_id", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("county", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("kyc_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credit_score", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_active_role", "users", ["is_active", "role"], unique=False)
    op.create_index("idx_user_email_deleted", "users", ["email", "deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "orders",
        sa.Column("side", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("order_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("fee", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_order_asset_status", "orders", ["asset_id", "status"], unique=False)
    op.create_index("idx_order_user_status", "orders", ["user_id", "status"], unique=False)
    op.create_index(op.f("ix_orders_asset_id"), "orders", ["asset_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "portfolio_items",
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("avg_buy_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "asset_id"),
    )
    op.create_index(
        op.f("ix_portfolio_items_asset_id"),
        "portfolio_items",
        ["asset_id"],
        unique=False,
    )
    op.create_index(op.f("ix_portfolio_items_user_id"), "portfolio_items", ["user_id"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("volume", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ph_asset_ts", "price_history", ["asset_id", "timestamp"], unique=False)
    op.create_index(op.f("ix_price_history_asset_id"), "price_history", ["asset_id"], unique=False)
    op.create_index(op.f("ix_price_history_timestamp"), "price_history", ["timestamp"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("balance", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("locked_balance", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "currency"),
    )
    op.create_index(op.f("ix_wallets_currency"), "wallets", ["currency"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("side", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("fee", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("total", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trade_asset_ts", "trades", ["asset_id", "executed_at"], unique=False)
    op.create_index(op.f("ix_trades_asset_id"), "trades", ["asset_id"], unique=False)
    op.create_index(op.f("ix_trades_order_id"), "trades", ["order_id"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tx_user_type", "transactions", ["user_id", "type"], unique=False)
    op.create_index(op.f("ix_transactions_type"), "transactions", ["type"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(op.f("ix_transactions_wallet_id"), "transactions", ["wallet_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_wallet_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index("idx_tx_user_type", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_order_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_asset_id"), table_name="trades")
    op.drop_index("idx_trade_asset_ts", table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_currency"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_price_history_timestamp"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_asset_id"), table_name="price_history")
    op.drop_index("idx_ph_asset_ts", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_portfolio_items_user_id"), table_name="portfolio_items")
    op.drop_index(op.f("ix_portfolio_items_asset_id"), table_name="portfolio_items")
    op.drop_table("portfolio_items")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_asset_id"), table_name="orders")
    op.drop_index("idx_order_user_status", table_name="orders")
    op.drop_index("idx_order_asset_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_user_email_deleted", table_name="users")
    op.drop_index("idx_user_active_role", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
